// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDovJSRNV9cRIodIokYESbI5wH6xRC6His',
    appId: '1:314843853869:web:66cbfb1794075edb4f74a4',
    messagingSenderId: '314843853869',
    projectId: 'coupon-d52b2',
    authDomain: 'coupon-d52b2.firebaseapp.com',
    storageBucket: 'coupon-d52b2.appspot.com',
    measurementId: 'G-KSYGRLQEM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsK3Pi9_3tsBwVJRyAGL2_zeOxUpLXYJc',
    appId: '1:314843853869:android:ae7796c24b3a81f04f74a4',
    messagingSenderId: '314843853869',
    projectId: 'coupon-d52b2',
    storageBucket: 'coupon-d52b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtRC28Gffuc-P9W1zDYTghFdb87hySlrk',
    appId: '1:314843853869:ios:ee83d8a70d78df7b4f74a4',
    messagingSenderId: '314843853869',
    projectId: 'coupon-d52b2',
    storageBucket: 'coupon-d52b2.appspot.com',
    androidClientId: '314843853869-hr3v1cl1nfcfcs2q3bk9eqf5l6s91kfj.apps.googleusercontent.com',
    iosClientId: '314843853869-9ei03c2d3eab0hmst74kdab812p5s5kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.coupon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtRC28Gffuc-P9W1zDYTghFdb87hySlrk',
    appId: '1:314843853869:ios:ee83d8a70d78df7b4f74a4',
    messagingSenderId: '314843853869',
    projectId: 'coupon-d52b2',
    storageBucket: 'coupon-d52b2.appspot.com',
    androidClientId: '314843853869-hr3v1cl1nfcfcs2q3bk9eqf5l6s91kfj.apps.googleusercontent.com',
    iosClientId: '314843853869-9ei03c2d3eab0hmst74kdab812p5s5kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.coupon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDovJSRNV9cRIodIokYESbI5wH6xRC6His',
    appId: '1:314843853869:web:1eef26ce022081b24f74a4',
    messagingSenderId: '314843853869',
    projectId: 'coupon-d52b2',
    authDomain: 'coupon-d52b2.firebaseapp.com',
    storageBucket: 'coupon-d52b2.appspot.com',
    measurementId: 'G-YL6TM1ZDLY',
  );
}
